import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

driver=webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(1500)
driver.get("https://regqc.sifyitest.com/pmcfeb23/reg_details.php?q=MTU4YzAzMWY3YmM5MTBmYWI3ZGFkNGUwMTAyYzg1N2N8MjczMDAwMDE5")
validate_your_details=driver.find_element(By.ID,"Recheck")
validate_your_details.click()
cadre=Select(driver.find_element(By.CSS_SELECTOR,"#cadre"))
cadre.select_by_index(1)
Designation=Select(driver.find_element(By.XPATH,"//*[@id='designation']"))
Designation.select_by_index(1)
category=driver.find_element(By.XPATH,"//tbody//tr[@class='tb-r2']//div//div[1]//input[1]").click()
Applied_category=driver.find_element(By.CSS_SELECTOR,"input[value='SC'][name='appldcategory']").click()
Disability_40percent_or_above=driver.find_element(By.CSS_SELECTOR,"input[value='Y'][name='optdisability']").click()
driver.find_element(By.CSS_SELECTOR,"input[value='Y'][name='pmc_employee']").click()
driver.find_element(By.CSS_SELECTOR,"input[value='Y'][name='castcertificate']").click()
driver.find_element(By.CSS_SELECTOR,"input[value='Y'][name='castvalcert']").click()
driver.find_element(By.CSS_SELECTOR,"input[value='Y'][name='govt_employee']").click()
driver.find_element(By.CSS_SELECTOR,"input[value='Y'][name='domicile']").click()
driver.find_element(By.CSS_SELECTOR,"input[value='Y'][name='freedom_fighter']").click()
driver.find_element(By.CSS_SELECTOR,"input[value='Y'][name='optminority']").click()
driver.find_element(By.CSS_SELECTOR,"input[value='Y'][name='farmer_suicide']").click()
Religion=Select(driver.find_element(By.XPATH,"//select[@id='religion']"))
Religion.select_by_index(1)
Centre=Select(driver.find_element(By.XPATH,"//select[@id='selexamcentre']"))
Centre.select_by_index(1)
Day=Select(driver.find_element(By.XPATH,"//select[@id='seldobday']"))
Day.select_by_index(1)
Month=Select(driver.find_element(By.XPATH,"//select[@id='seldobmon']"))
Month.select_by_index(1)
Year=Select(driver.find_element(By.XPATH,"//select[@id='seldobmon']"))
Year.select_by_index(1)
Gender=driver.find_element(By.CSS_SELECTOR,"input[value='M'][name='optsex']")
Gender.click()
Twin_Bro_sis=driver.find_element(By.CSS_SELECTOR,"input[value='N'][name='twinbrosis']")
Twin_Bro_sis.click()
driver.find_element(By.XPATH,"//input[@value='Unmarried']").click()
Father_name=driver.find_element(By.XPATH,"//input[@id='fatherfirstname']")
Father_name.send_keys("Haaaaaaaaa")
Mother_name=driver.find_element(By.XPATH,"//input[@id='fatherfirstname']")
Mother_name.send_keys("Haaaa")
#Spouse_name=driver.find_element(By.XPATH,"//input[@id='spousefirstname']")
#Spouse_name.send_keys("Haaaaaaaaa")
Address1=driver.find_element(By.XPATH,"//input[@id='txtaddress1']")
Address1.send_keys("HHHHHaaa")
District=driver.find_element(By.XPATH,"//input[@id='txtdistrict']")
District.send_keys("Ha")
State=Select(driver.find_element(By.XPATH,"//select[@id='txtstate']"))
State.select_by_index(2)
pincode=driver.find_element(By.XPATH,"//input[@id='txtpin']")
pincode.send_keys(524303)
time.sleep(5)
#driver.find_element(By.XPATH,"//input[@id='same_presentadd']").click()
Save_and_Next=driver.find_element(By.XPATH,"(//input[@id='FinalSubmit'])[2]")
Save_and_Next.click()
time.sleep(5)
Back=driver.find_element(By.CSS_SELECTOR,"a[type='button']")
Back.click()
time.sleep(2)


